version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - CHATTER_SECRET=${CHATTER_SECRET}
      - CHATTER_DB_DIR=/app/db
    ports:
      - 8000:8000
    volumes:
      - database:/app/db

  frontend:
    build:
      context: ./frontend
      args:
        CHATTER_API_URL: ${CHATTER_API_URL}
    ports:
      - 8080:8080

volumes:
  database:
