version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      - CHATTER_SECRET=${CHATTER_SECRET}

  frontend:
    build: ./frontend
    ports:
      - 8080:8080
